-- 1. Creación de la tabla CATEGORIAS (Necesaria para la clave ajena)
-- La clave ajena (FOREIGN KEY) debe referenciar a una clave primaria (PRIMARY KEY).
--  http://localhost:8080/h2-console
CREATE TABLE IF NOT EXISTS CATEGORIAS (
    id BIGINT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);


-- 2. Creación de la tabla PRODUCTOS
CREATE TABLE IF NOT EXISTS PRODUCTOS (
    -- Clave Primaria
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(1000),
    precio DECIMAL(10, 2) NOT NULL, 
    
    peso DECIMAL(10, 3),        
    altura DECIMAL(10, 2),      
    anchura DECIMAL(10, 2),
    profundidad DECIMAL(10, 2),


    fecha_creacion TIMESTAMP NOT NULL,
    
    -- Clave Ajena (FOREIGN KEY)
    categoria_id BIGINT,
    FOREIGN KEY (categoria_id) REFERENCES CATEGORIAS(id)
);