package es.etg.daw.dawes.java.rest.restfull.productos.infraestructure.db.jpa.entity;

import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.Builder;
import lombok.Data;
import lombok.AllArgsConstructor;


@Entity
@Data
@Builder
@AllArgsConstructor
@Table(name = "CATEGORIAS")
public class CategoriaJpaEntity {

    // Usamos IDENTITY. H2 lo mapea a 'GENERATED BY DEFAULT AS IDENTITY'.
    // MySQL lo mapea a 'AUTO_INCREMENT'. Es el método más portable.
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    @Column(name = "nombre", nullable = false, length = 100)
    private String nombre;

    // Relación One-to-Many: Lado no propietario
    // Mapeada por el campo "categoria" en la entidad Producto.
    @OneToMany(mappedBy = "categoria", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<ProductoJpaEntity> productos = new ArrayList<ProductoJpaEntity>();

    // --- Constructores ---

    public CategoriaJpaEntity() {
    }

    public CategoriaJpaEntity(Integer id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    //Métodos auxiliares para sincronizra productos y categorias
    public void addProducto(ProductoJpaEntity producto) {
        this.productos.add(producto);
        producto.setCategoria(this); // Sincroniza el lado Producto
    }

    public void removeProducto(ProductoJpaEntity producto) {
        this.productos.remove(producto);
        producto.setCategoria(null); // Desvincula el Producto
    }
    
}